import type { GetStaticProps, NextPage } from 'next'
import { useEffect, useState,FC } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import dataFetcher from './api/dataFatcher'
import { Character, getCharacterResults } from '../utility/types'
import imageLoader from '../utility/imageLoader'

export const getStaticProps: GetStaticProps = async (context) => {
  const res = await fetch("https://rickandmortyapi.com/api/character");
  const { results }: getCharacterResults = await res.json();
  // console.log(res)
  return {
    props: {
      characters: results
    }
  }
}
const Home: NextPage<{ characters: Character[] }> = ({ characters }) => {
  const [list, setList] = useState<Character[]>([])

  useEffect(()=>{
    const getData = async () => {
      const resp = await dataFetcher()
      // console.log(resp)
      setList(resp)
    }

    getData()
  },[])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* {JSON.stringify(characters)} */}
      {characters.map((character, i) => {
        return <div key={character.id}>
          <Link href={`/character/${character.id}`}>
            <a>
          <h3>{character.name}</h3>
            </a>
          </Link>

          <Image 
          loader={imageLoader}
          unoptimized
          src={character.image} alt={character.name}
            width="200" height="200" />
        </div>

      })}
      {
        list.map((characters)=>{
          return <>
          <div key={characters.id}> {characters.name}
          <Image  loader={imageLoader}
          unoptimized
          src={characters.image} alt={characters.name}
            width="200" height="200" />
          </div>
          </>
        })
      }

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image loader={imageLoader} src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
